name: "dummy-template"

on: workflow_dispatch

jobs:
  noop_job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.4.0

      - name: Set up QEMU environment
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        if: false
        uses: docker/login-action@v1.12.0
